name: Generate trophy card

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate trophy.svg
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: ${{ github.repository_owner }}
          file: dist/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: dracula
          max-cols: -1
          max-rows: 1
          margin-width: 8
          margin-height: 8
          no-background: false
          no-frame: false

      - name: generate trophy.svg
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: ${{ github.repository_owner }}
          file: dist/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: dracula
          max-cols: 6 # Change this from -1 to 6 (or 0 for automatic columns)
          max-rows: 2 # Increased rows slightly so trophies don't get cut off if you have more than 6
          margin-width: 8
          margin-height: 8
          no-background: false
          no-frame: false
       
